fix: AttributeError: 'TTS' object has no attribute 'speakers' (#2)
Hard-code the intended speaker name rather than using the tts.speakers appraoch that only works when using the `FoamoftheSea` fork with the required bug fixes.

Note that this change alone does _not_ dissolve the need to install `TTS` using that fork, since the `lingonaut-python` code also uses `verbose=False` which is not supported by the upstream `TTS` repo. Until #5 is resolved, users _must_ install `lingonaut-python` using the conda `environment.yaml` which will install `TTS` using the fork and avoid compatibility issues.

---------

Co-authored-by: webbrain-dev <327187637+webbrain-dev@users.noreply.github.com>
Co-authored-by: Nate Cibik <50897218+FoamoftheSea@users.noreply.github.com>